---
## Author
author:
  name: Сергеев Даниил Олегович
  degrees: DSc
  orcid: 0000-0002-0877-7063
  email: 1132246837@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

## Title
title: "Индивидуальный проект"
subtitle: "Этап №4"
license: "CC BY"
---

# Цель работы

Целью данной работы является использование приложения BurpSuite в рамках индивидуального проекта. [@tuis]

# Ход выполнения лабораторной работы

## Запуск DVWA

Будем тестировать BurpSuite на основе DVWA, установленного на прошлых этапах. Запустим веб-приложение и BurpSuite.
```bash
service apache2 start
service mariadb start
```

Burp Suite представляет собой набор мощных инструментов безопасности веб-приложений, которые демонстрируют реальные возможности злоумышленника, проникающего в веб-приложения. [@kali-book]



# Вывод

В результате выполнения лабораторной работы был испытан базовый сканер безопасности веб-сервера nikto на основе уязвимого DVWA. Были исследованы возможные уязвимости, которые нашлись внутри данного веб-приложения.

# Список литературы{.unnumbered}

::: {#refs}
:::
